### ISSUE TITLE
As an authenticated user, when I register a restaurant with no slug, a slug will be automatically generated.

### ISSUE THREAD

**Issue by vanegomez** [vanegomez/supper_skip#1]
As a registered user
when I visit root url
and I click on "register a new restaurant/store"
and I fill in a (unique) name
and I fill in description
and I click "Create Restaurant"
then and I'm back on '/restaurantname'
and I see Restaurant's Name displayed

--- since no slug was entered, one was generated for them using dash-er-ized-lower-cased version of the restaurant name

**Comment by ghost** [comment]
set up slug in routes :)
